#!/bin/bash
# 修复 YUM 源配置脚本
# 参考 playground 项目优化
# author: RaynLiu
# email: liuyu1_j6go@stu.cqie.edu.cn
# Copyright © 2025 RaynLiu

# ==========================================
# 颜色和日志函数
# ==========================================
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log_info() {
    echo -e "${GREEN}[✓]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[⚠]${NC} $1"
}

log_step() {
    echo -e "${CYAN}[→]${NC} $1"
}

# ==========================================
# 核心函数：配置阿里云镜像源（参考 playground）
# ==========================================
set_centos_repo_to_aliyun() {
    local repo_file="/etc/yum.repos.d/CentOS-Base.repo"
    
    # 1. 备份原有源（如果存在）
    if [ -f "${repo_file}" ]; then
        local backup_file="${repo_file}.bak.$(date +%Y%m%d_%H%M%S)"
        cp -a "${repo_file}" "${backup_file}" 2>/dev/null && \
            log_info "已备份原有源: ${backup_file}"
    fi
    
    # 2. 写入完整的阿里云镜像源配置
    log_step "配置阿里云 CentOS 镜像源..."
    cat > "${repo_file}" << 'EOF'
# CentOS-Base.repo
# 阿里云镜像源 - 自动配置
# Generated by setup_cdh_cluster - RaynLiu

[base]
name=CentOS-$releasever - Base
baseurl=https://mirrors.aliyun.com/centos/$releasever/os/$basearch/
gpgcheck=0
enabled=1
skip_if_unavailable=1

[updates]
name=CentOS-$releasever - Updates
baseurl=https://mirrors.aliyun.com/centos/$releasever/updates/$basearch/
gpgcheck=0
enabled=1
skip_if_unavailable=1

[extras]
name=CentOS-$releasever - Extras
baseurl=https://mirrors.aliyun.com/centos/$releasever/extras/$basearch/
gpgcheck=0
enabled=1
skip_if_unavailable=1

[centosplus]
name=CentOS-$releasever - Plus
baseurl=https://mirrors.aliyun.com/centos/$releasever/centosplus/$basearch/
gpgcheck=0
enabled=0
skip_if_unavailable=1

[contrib]
name=CentOS-$releasever - Contrib
baseurl=https://mirrors.aliyun.com/centos/$releasever/contrib/$basearch/
gpgcheck=0
enabled=0
skip_if_unavailable=1
EOF
    
    if [ $? -eq 0 ]; then
        log_info "CentOS Base 源配置成功"
    else
        log_warn "CentOS Base 源配置可能失败"
        return 1
    fi
}

# ==========================================
# 配置 EPEL 源
# ==========================================
set_epel_repo() {
    local epel_file="/etc/yum.repos.d/epel.repo"
    
    # 1. 备份原有 EPEL 源（如果存在）
    if [ -f "${epel_file}" ]; then
        local backup_file="${epel_file}.bak.$(date +%Y%m%d_%H%M%S)"
        cp -a "${epel_file}" "${backup_file}" 2>/dev/null && \
            log_info "已备份原有 EPEL 源: ${backup_file}"
    fi
    
    # 2. 写入 EPEL 源配置
    log_step "配置阿里云 EPEL 源..."
    cat > "${epel_file}" << 'EOF'
# EPEL repo
# 阿里云 EPEL 镜像源
# Generated by setup_cdh_cluster - RaynLiu

[epel]
name=Extra Packages for Enterprise Linux $releasever - $basearch
baseurl=https://mirrors.aliyun.com/epel/$releasever/$basearch
gpgcheck=0
enabled=1
skip_if_unavailable=1

[epel-debuginfo]
name=Extra Packages for Enterprise Linux $releasever - $basearch - Debug
baseurl=https://mirrors.aliyun.com/epel/$releasever/$basearch/debug
gpgcheck=0
enabled=0
skip_if_unavailable=1

[epel-source]
name=Extra Packages for Enterprise Linux $releasever - $basearch - Source
baseurl=https://mirrors.aliyun.com/epel/$releasever/SRPMS
gpgcheck=0
enabled=0
skip_if_unavailable=1
EOF
    
    if [ $? -eq 0 ]; then
        log_info "EPEL 源配置成功"
    else
        log_warn "EPEL 源配置可能失败"
        return 1
    fi
}

# ==========================================
# 主执行流程
# ==========================================
main() {
    echo ""
    log_info "开始修复 YUM 源配置..."
    echo ""
    
    # 1. 清理旧的 Ansible 源（避免冲突）
    log_step "清理旧的 Ansible 源..."
    rm -f /etc/yum.repos.d/*ansible*.repo 2>/dev/null
    rm -f /etc/yum.repos.d/CentOS-Ansible*.repo 2>/dev/null
    
    # 2. 配置 CentOS Base 源
    set_centos_repo_to_aliyun || {
        log_warn "CentOS Base 源配置失败，但继续执行..."
    }
    
    # 3. 配置 EPEL 源
    set_epel_repo || {
        log_warn "EPEL 源配置失败，但继续执行..."
    }
    
    echo ""
    log_info "YUM 源配置完成！"
    echo ""
}

# 执行主函数
main
